services:
  postgres:
    image: 'postgres:14.9'
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    
