CREATE TABLE IF NOT EXISTS category
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uc_category_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname VARCHAR(255),
    name     VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_nickname UNIQUE (nickname)
);

CREATE TABLE IF NOT EXISTS channel
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    image       VARCHAR(255),
    author_id   BIGINT,
    create_date date,
    category_id BIGINT,
    language    VARCHAR(255),
    CONSTRAINT pk_channel PRIMARY KEY (id),
    CONSTRAINT uc_channel_title UNIQUE (title),
    CONSTRAINT FK_CHANNEL_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES "user" (id) on delete cascade ,
    CONSTRAINT FK_CHANNEL_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE IF NOT EXISTS user_channel_subscription
(
    channel_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_user_channel_subscription PRIMARY KEY (channel_id, user_id),
    CONSTRAINT fk_usechasub_on_channel FOREIGN KEY (channel_id) REFERENCES channel (id) on delete cascade ,
    CONSTRAINT fk_usechasub_on_user FOREIGN KEY (user_id) REFERENCES "user" (id) on delete cascade
);



